name: Test Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test_suite:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: mkdir -p testResults
      - name: Run POSTMAN collection
      continue-on-error: true
        run: |
          newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults 